const promiseReject = new Promise((resolve, reject) => {
setTimeout(() => reject("Promise rejected!"), 1000);
});
promiseReject.catch(error => console.error(error));